In [2]:
import pandas as pd

In [6]:

file_address = '../Data/zip/longislandzip.csv'

df1 = pd.read_csv(file_address)

In [5]:


file_address = '../Data/zip/New_York_State_ZIP_Codes-County_FIPS_Cross-Reference.csv'

df2 = pd.read_csv(file_address)

In [8]:

file_address = '../Data/zip/nyslongislandzip.csv'

df3 = pd.read_csv(file_address)

In [7]:

file_address = '../Data/zip/zip_code_database.csv'

df4 = pd.read_csv(file_address)

In [22]:
len(df1)

220

In [9]:
df1

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population_2015
0,501,UNIQUE,0,Holtsville,NaN,I R S Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Irs Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,6390,PO BOX,0,Fishers Island,Fishers Isle,NaN,NY,Suffolk County,America/New_York,631,NaN,US,41.27,-71.99,286
3,11001,STANDARD,0,Floral Park,"Bellerose Vil, Bellerose Village, S Floral Par...","Bellerose Terrace, Bellrose Village, So Floral...",NY,Nassau County,America/New_York,"516,718",NaN,US,40.72,-73.70,26970
4,11003,STANDARD,0,Elmont,"Alden Manor, Floral Park, Meacham","Argo Village, Locustwood",NY,Nassau County,America/New_York,516,NaN,US,40.70,-73.70,44160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,11975,PO BOX,0,Wainscott,NaN,NaN,NY,Suffolk County,America/New_York,631,NaN,US,40.94,-72.24,1196
216,11976,STANDARD,0,Water Mill,NaN,"Watermill, Wtr Mill",NY,Suffolk County,America/New_York,631,NaN,US,40.92,-72.34,2070
217,11977,STANDARD,0,Westhampton,NaN,"W Hampton, West Hampton",NY,Suffolk County,America/New_York,631,NaN,US,40.83,-72.68,2380
218,11978,STANDARD,0,Westhampton Beach,W Hampton Bch,"Quioque, W Hampton Beach, West Hampton Beach, ...",NY,Suffolk County,America/New_York,631,NaN,US,40.83,-72.65,3420
219,11980,STANDARD,0,Yaphank,NaN,Carver Park,NY,Suffolk County,America/New_York,631,NaN,US,40.83,-72.92,3960

In [16]:
df2[df2['County Name'].isin(['Suffolk','Nassau'])]

     County Name  State FIPS  County Code  County FIPS  ZIP Code   File Date
1079      Nassau          36           59        36059     11001  07/25/2007
1080      Nassau          36           59        36059     11002  07/25/2007
1081      Nassau          36           59        36059     11003  07/25/2007
1082      Nassau          36           59        36059     11010  07/25/2007
1083      Nassau          36           59        36059     11020  07/25/2007
...          ...         ...          ...          ...       ...         ...
2161     Suffolk          36          103        36103     11975  07/25/2007
2162     Suffolk          36          103        36103     11976  07/25/2007
2163     Suffolk          36          103        36103     11977  07/25/2007
2164     Suffolk          36          103        36103     11978  07/25/2007
2165     Suffolk          36          103        36103     11980  07/25/2007

[219 rows x 6 columns]

In [17]:
df3

    County Name  State FIPS  County Code  County FIPS  ZIP Code  File Date
0        Nassau          36           59        36059     11001  7/25/2007
1        Nassau          36           59        36059     11002  7/25/2007
2        Nassau          36           59        36059     11003  7/25/2007
3        Nassau          36           59        36059     11010  7/25/2007
4        Nassau          36           59        36059     11020  7/25/2007
..          ...         ...          ...          ...       ...        ...
214     Suffolk          36          103        36103     11975  7/25/2007
215     Suffolk          36          103        36103     11976  7/25/2007
216     Suffolk          36          103        36103     11977  7/25/2007
217     Suffolk          36          103        36103     11978  7/25/2007
218     Suffolk          36          103        36103     11980  7/25/2007

[219 rows x 6 columns]

In [20]:
df4

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population_2015
0,501,UNIQUE,0,Holtsville,NaN,I R S Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Irs Service Center,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,601,STANDARD,0,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas Municipio,America/Puerto_Rico,"787,939",NaN,US,18.16,-66.72,0
3,602,STANDARD,0,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,Aguada Municipio,America/Puerto_Rico,"787,939",NaN,US,18.38,-67.18,0
4,603,STANDARD,0,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla Municipio,America/Puerto_Rico,787,NaN,US,18.43,-67.15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42627,99926,PO BOX,0,Metlakatla,NaN,NaN,AK,Prince of Wales-Outer Ketchikan Borough,America/Metlakatla,907,NaN,US,55.14,-131.49,1140
42628,99927,PO BOX,0,Point Baker,NaN,NaN,AK,Prince of Wales-Hyder Census Area,America/Sitka,907,NaN,US,56.30,-133.57,48
42629,99928,PO BOX,0,Ward Cove,NaN,NaN,AK,Ketchikan Gateway Borough,America/Sitka,907,NaN,US,55.45,-131.79,1530
42630,99929,PO BOX,0,Wrangell,NaN,NaN,AK,Wrangell City and Borough,America/Sitka,907,NaN,US,56.41,-131.61,2145
42631,99950,PO BOX,0,Ketchikan,"Edna Bay, Kasaan",NaN,AK,Prince of Wales-Outer Ketchikan Borough,America/Sitka,907,NaN,US,55.34,-131.64,262

In [21]:
df4['county'].unique()

array(['Suffolk County', 'Adjuntas Municipio', 'Aguada Municipio', ...,
       'Wrangell City and Borough', 'Prince of Wales-Hyder Census Area',
       'Prince of Wales-Outer Ketchikan Borough'], dtype=object)